name: Tests

on:
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Output version
        id: version
        run: |
          echo ::set-output name=version::$(node -e "console.log(require('./package.json').version);")
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup Yarn
        run: npm install -g yarn@1.22.5

      - name: Download dependencies
        run: yarn install

      - name: "Build :: prod and pack"
        run: yarn run prod

      - name: Less is more - Should pass
        if: matrix.os == 'ubuntu-latest'
        uses: caponetto/less-is-more@v0.0.6
        with:
          released_artifact_name: test_release_*
          artifact_path: "**/test_artifact_*.vsix"
          max_increase_percentage: 70
          github_token: ${{ secrets.BASIC_TOKEN }}

      - name: Less is more - Should pass
        if: matrix.os == 'macos-latest'
        uses: caponetto/less-is-more@v0.0.6
        with:
          released_artifact_name: test_release_*
          artifact_path: "**/test_artifact_*.vsix"
          max_increase_percentage: 59
          github_token: ${{ secrets.BASIC_TOKEN }}

      - name: Less is more - Should fail
        if: matrix.os == 'ubuntu-latest'
        uses: caponetto/less-is-more@v0.0.6
        with:
          released_artifact_name: test_release_*
          artifact_path: "**/test_artifact_*.vsix"
          max_increase_percentage: 58
          github_token: ${{ secrets.BASIC_TOKEN }}
          
      - name: Less is more - Should pass
        if: matrix.os == 'windows-latest'
        uses: caponetto/less-is-more@v0.0.6
        with:
          released_artifact_name: test_release_*
          artifact_path: "**/test_artifact_*.vsix"
          max_increase_percentage: 10
          github_token: ${{ secrets.BASIC_TOKEN }}
          fail_execution: false
